apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: smartlogix
  labels:
    app: krakend
    service: gateway
    component: api-gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
        service: gateway
        component: api-gateway
    spec:
      containers:
      - name: krakend
        image: krakend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: FC_ENABLE
          value: "1"
        ports:
        - containerPort: 8080
        - containerPort: 8090
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config