--
-- PostgreSQL database dump
--

\restrict XOGZn3sg1K7ZbtX1Ht3kswaXdygxg96gg0KK5aG5YOIop1k5NEkcpRSgLABunMF

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-17 18:02:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16405)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16404)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4857 (class 2606 OID 16415)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


-- Completed on 2026-05-17 18:02:02

--
-- PostgreSQL database dump complete
--

\unrestrict XOGZn3sg1K7ZbtX1Ht3kswaXdygxg96gg0KK5aG5YOIop1k5NEkcpRSgLABunMF

