--
-- PostgreSQL database dump
--

\restrict 7qXibn175dK3u007iJrmr6gC0QswXsOINcVLjb2xYf3JaPtx8JQWIIBcEpvjuXm

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-17 18:00:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16391)
-- Name: inventory_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_item (
    id_item bigint NOT NULL,
    bodega character varying(255) NOT NULL,
    cantidad integer NOT NULL,
    descripcion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16390)
-- Name: inventory_item_id_item_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_item ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_item_id_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4857 (class 2606 OID 16403)
-- Name: inventory_item inventory_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_item
    ADD CONSTRAINT inventory_item_pkey PRIMARY KEY (id_item);


-- Completed on 2026-05-17 18:00:57

--
-- PostgreSQL database dump complete
--

\unrestrict 7qXibn175dK3u007iJrmr6gC0QswXsOINcVLjb2xYf3JaPtx8JQWIIBcEpvjuXm

