apiVersion: v1
kind: Service
metadata:
  name: ms-orders
  namespace: smartlogix
  labels:
    app: ms-orders
    service: backend
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: http
  selector:
    app: ms-orders