apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: smartlogix
  labels:
    app: inventory-db
    service: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: inventory-db