apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pvc
  namespace: smartlogix
  labels:
    app: inventory-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard