apiVersion: v1
kind: Service
metadata:
  name: ms-inventory
  namespace: smartlogix
  labels:
    app: ms-inventory
    service: backend
spec:
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: http
  selector:
    app: ms-inventory