apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: smartlogix
  labels:
    app: bff
    service: backend
    component: bff-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
        service: backend
        component: bff-service
    spec:
      containers:
      - name: bff
        image: bff:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: USER_SERVICE_URL
          value: "http://ms-user:9090"
        - name: INVENTORY_SERVICE_URL
          value: "http://ms-inventory:9091"
        - name: ORDERS_SERVICE_URL
          value: "http://ms-orders:9092"
        - name: RESTOCK_SERVICE_URL
          value: "http://ms-restock:9093"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10