apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: bff:3.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: USER_SERVICE_URL
              value: http://ms-user:9090
            - name: INVENTORY_SERVICE_URL
              value: http://ms-inventory:9091
            - name: ORDERS_SERVICE_URL
              value: http://ms-orders:9092
            - name: RESTOCK_SERVICE_URL
              value: http://ms-restock:9093