apiVersion: v1
kind: Secret
metadata:
  name: brevo-secrets
  namespace: smartlogix
type: Opaque
data:
  api-key: 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