apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: userdb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: userpass123
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: ms-user:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://user-db:5432/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: userpass123